### ISSUE TITLE
[SystemManager] text flickers when window is moved around

### ISSUE THREAD

**Issue by diversys** [X547/HaikuUtils#10]
hrev54790 x86-64 running in VMware Fusion.

**Comment by diversys** [comment]
Could it be related to https://dev.haiku-os.org/ticket/15631?

**Comment by X547** [comment]
This is [#15631](https://dev.haiku-os.org/ticket/15631) and fixing will require third screen buffer or hardware screen-to-screen blit support with overlapping. Nothing to be done in SystemManager.

**Comment by diversys** [comment]
Thanks for the info, closing then!

**Comment by X547** [comment]
[#15920](https://dev.haiku-os.org/ticket/15920) tracks all remaining Haiku flickering problems. Problem 3 ([#15574](https://dev.haiku-os.org/ticket/15574)) is already solved.
