### ISSUE TITLE
Services doesn't list "desktop" target

### ISSUE THREAD

**Issue by diversys** [X547/HaikuUtils#2]
https://git.haiku-os.org/haiku/tree/data/launch/user#n1

**Comment by X547** [comment]
Works for me in hrev54738. Can you attach screenshot?

**Comment by diversys** [comment]
Ah, it's in a column. I was looking for a single "desktop" target in the first column which you can start like with `launch_roster start desktop`.
I was trying to repro https://dev.haiku-os.org/ticket/15563.

**Comment by X547** [comment]
Maybe targets should be reorganized in a tree (target -> service).

**Comment by diversys** [comment]
Maybe, but I also like the simplicity of the current view :) Need to see how it looks.

**Comment by X547** [comment]
Implemented in https://github.com/X547/HaikuUtils/commit/f82d9adaed2aa674403f4614c39f6bb2d399452d.

**Comment by diversys** [comment]
Looks good, thanks! :)
